version: '3.2'
services:
  arke:
    build:
      context: .
    image: fonoster/arke:latest
    environment:
      ARKE_EXTERN_ADDR: ${ARKE_EXTERN_ADDR}
      ARKE_DS_PROVIDER: redis_data_provider
      ARKE_DS_PARAMETERS: "host=redis,port=6379"
    ports:
      - '5060:5060'
      - '5060:5060/udp'
      - '5061:5061'
      - '5062:5062'
      - '5063:5063'
      - '4567:4567'
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - '6379:6379'
