version: '3'
services:
  sipio:
    build:
      context: .
    image: fonoster/sipio:latest
    environment:
      - EXTERN_ADDR=${EXTERN_ADDR}
    ports:
      - '5060:5060'
      - '5060:5060/udp'
      - '5061:5061'
      - '5062:5062'
      - '5063:5063'
