version: '3'
services:
  sipio:
    build:
      context: .
    image: fonoster/sipio:latest
    environment:
      - SIPIO_EXTERN_ADDR=${SIPIO_EXTERN_ADDR}
    ports:
      - '5060:5060'
      - '5060:5060/udp'
      - '5061:5061'
      - '5062:5062'
      - '5063:5063'
      - '4567:4567'
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - '6390:6390'
      - '6379:6379'
