- apiVersion: v1draft1
  kind: Agent
  metadata:
<<<<<<< HEAD
    name: Whatever Agent Name
=======
    name: John Doe
>>>>>>> df6c1f4a1b59147d17699617204b9fd54be05395
  spec:
    credentials:
      username: '1001'
      secret: '1234'
    domains: [sip.local]
- apiVersion: v1draft1
  kind: Agent
  metadata:
<<<<<<< HEAD
    name: Another Agent Name
=======
    name: Janie Doe
>>>>>>> df6c1f4a1b59147d17699617204b9fd54be05395
  spec:
    credentials:
      username: '1002'
      secret: '1234'
    domains: [sip.local]
