name: routr-server
base: core18
version: 1.0.0-rc4
license: MIT
summary: Next-generation SIP Server
description: |
  Routr – a lightweight sip proxy, location server, and registrar that provides
  a reliable and scalable SIP infrastructure for telephony carriers,
  communication service providers, and integrators. It also provides with
  capabilities that are suitable for the enterprise and personal needs.
assumes: [snapd2.42]
grade: devel
confinement: strict

apps:
  routr-server:
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-8-openjdk-amd64
      ROUTR_SALT_FILE: $SNAP_USER_DATA/.routr.salt
    command: routr-server
    plugs: [network, network-bind]
  service:
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-8-openjdk-amd64
      ROUTR_SALT_FILE: $SNAP_USER_DATA/.routr.salt      
    command: routr-server
    daemon: simple
    plugs: [network, network-bind]

parts:
  build:
    plugin: dump
    source: https://github.com/fonoster/routr/releases/download/$SNAPCRAFT_PROJECT_VERSION/routr-$SNAPCRAFT_PROJECT_VERSION_linux-x64_bin.tar.gz
    override-build: |
      cp -a * $SNAPCRAFT_PART_INSTALL/
      rm -rf $SNAPCRAFT_PART_INSTALL/jre
      rm -rf $SNAPCRAFT_PART_INSTALL/config
      rm $SNAPCRAFT_PART_INSTALL/routr.bat
      mv $SNAPCRAFT_PART_INSTALL/routr $SNAPCRAFT_PART_INSTALL/routr-server
    stage-packages:
      - openjdk-8-jdk
  prepare:
      plugin: dump
      source: resources/
      organize:
          config.yml: config/config.yml
          log4j2.yml: config/log4j2.yml
