name: routr-server
base: core18
version: #{ROUTR_VERSION}
license: MIT
summary: Next-generation SIP Server
description: |
  Routr – a lightweight sip proxy, location server, and registrar that provides
  a reliable and scalable SIP infrastructure for telephony carriers,
  communication service providers, and integrators. It also provides with
  capabilities that are suitable for the enterprise and personal needs.
assumes: [snapd2.42]
grade: stable
confinement: strict

apps:
  routr-server:
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-8-openjdk-amd64
      ROUTR_DATA: $SNAP_USER_COMMON
      ROUTR_SALT_FILE: $SNAP_DATA/.routr.salt
      ROUTR_CONFIG_FILE: $SNAP_DATA/config/config.yml
      ROUTR_LOG4J2: $SNAP_DATA/config/log4j2.yml
    command: start.sh
    daemon: simple
    plugs: [network, network-bind, home]
  routr-redis:
    command: redis-server $SNAP_DATA/config/redis.conf
    daemon: simple
    plugs: [network, network-bind]

parts:
  configure:
    plugin: dump
    source: resources
    organize:
      config.yml: config/config.yml
      log4j2.yml: config/log4j2.yml
      redis.conf: config/redis.conf
  routr-server:
    after: [configure]
    plugin: dump
    source: https://github.com/fonoster/routr/releases/download/$SNAPCRAFT_PROJECT_VERSION/routr-$SNAPCRAFT_PROJECT_VERSION_linux-x64_bin.tar.gz
    override-build: |
      cp -a * $SNAPCRAFT_PART_INSTALL
      cd $SNAPCRAFT_PART_INSTALL
      rm -rf jre config/* routr.bat
      cp ../../configure/build/start.sh .
      cp -a ../../configure/build/*.yml config
      cp ../../configure/build/redis.conf config/redis.conf
    build-packages:
      - ca-certificates
      - ca-certificates-java
      - openjdk-8-jre-headless
    stage-packages:
      - openjdk-8-jre-headless
      - redis-server
