# Peers and Agents can register in Sip I/O location service
- kind: Agent
  apiVersion: v1
  metadata:
    name: Jhon Doe
  username: jhondoe
  secret: gJcxzr1v4zXUVXJ3
  domains:
    - ny.ocean.com
    - tx.ocean.com
- kind: Agent
  apiVersion: v1
  metadata:
    name: Janie Doe
  username: janiedoe
  secret: gJcxzr1v4zXUVXJ3
  domains:
    - ny.ocean.com
