# Peers and Agents can register in Sip I/O location service
- kind: Agent
  apiVersion: v1
  metadata:
    name: John Doe
  username: john
  secret: 1234
  domains:
    - sip.fonoster.com
- kind: Agent
  apiVersion: v1
  metadata:
    name: Janie Doe
  username: janie
  secret: 1234
  domains:
    - sip.fonoster.com
