# Peers and Agents can register in Sip I/O location service
- apiVersion: v1draft1
  kind: Agent
  metadata:
    name: John Doe
  spec:
    access:
      username: john
      secret: '1234'
    domains: [sip.ocean.com]
- kind: Agent
  apiVersion: v1draft1
  metadata:
    name: Janie Doe
  spec:
    access:
      username: janie
      secret: '1234'
    domains: [sip.ocean.com]