traceLevel: 10 # SIP stack logs
tcpPort: 5060
udpPort: 5060
tlsPort: 5061
wsPort: 5062
rest:
  port: 4567
  username: admin
  password: 1234

# Remove comment to deny all networks by default

#defaultDomainAcl:
#  deny:
#    - 0.0.0.0/1