transport: 'udp'
port: 5082
traceLevel: 10 # SIP stack logs
rest:
  port: 4567
  username: admin
  password: 1234

# Remove comment to deny all networks by default

#defaultDomainAcl:
#  deny:
#    - 0.0.0.0/1