# This is Sip I/O's general configuration file
general:
  traceLevel: 10
  tcpPort: 5060
  udpPort: 5060
  tlsPort: 5061
  wsPort: 5062
rest:
  port: 4567
  username: admin
  secret: 1234
  disable: false
