apiVersion: v1beta1
spec:
  transport:
    - protocol: udp
      port: 5060
    - protocol: tcp
      port: 5060
  dataSource:
    provider: 'redis_data_provider'
    parameters:
      host: '192.168.1.127'
      port: 6379
      secret: osopolar
