# This is Sip I/O's general configuration file

# SIP stack logs
traceLevel: 10

# Transport ports
tcpPort: 5060
udpPort: 5060
tlsPort: 5061
wsPort: 5062

# CLI Configuration
rest:
  port: 4567
  username: admin
  password: 1234
  disable: false
