apiVersion: v1draft1
spec:
  securityContext:
    keyStore: etc/certs/domains-cert.jks
    trustStore: etc/certs/domains-cert.jks
    keyStorePassword: 'password'
    keyStoreType: 'jks'
    debugging: false
  dataSource:
    provider: 'restful_data_provider'
    parameters:
      baseUrl: http://localhost:8080/v1/ctl
      username: admin
      secret: 308a002ab539471394a06ce710bc96c2
  transport:
    - protocol: udp
      port: 5060
    - protocol: tcp
      port: 5060
    - protocol: tls
      port: 5061
    - protocol: ws
      port: 5062
    - protocol: wss
      port: 5063
  logging:
    traceLevel: 0