- apiVersion: v1draft1
  kind: DID
  metadata:
    ref: DID0001
    gwRef: GW0001
    geoInfo:
      city: Columbus, GA
      country: USA
      countryISOCode: US
  spec:
    location:
      telUrl: 'tel:7062332323'
      aorLink: 'sip:john@sip.ocean.com'
