- apiVersion: v1draft1
  kind: DID
  metadata:
    gwRef: gweef506
    geoInfo:                  # Replace this using your DID's info
      city: City, State
      country: Country
      countryISOCode: US
  spec:
    location:
      telUrl: 'tel:0000000000'        # Use your DID number as giving by your provider
      aorLink: 'sip:1001@sip.local'
