- apiVersion: v1draft1
  kind: Domain
  metadata:
    name: Ocean Central Office
  spec:
    context:
      domainUri: sip.ocean.com
      egressPolicy:
        rule: .*        # See the Location Service Rules for information about this parameter
        didRef: DID0001