- apiVersion: v1beta1
  kind: Domain
  metadata:
    name: My Home or Office Setup
  spec:
    context:
      domainUri: sip3.local
      egressPolicy:
        rule: .*
        didRef: dd50baa5
- apiVersion: v1beta1
  kind: Domain
  metadata:
    name: Another Office
  spec:
    context:
      domainUri: sip2.local
