- apiVersion: v1draft1
  kind: Domain
  metadata:
    name: My Home or Office Setup
  spec:
    context:
      domainUri: sip.local
      egressPolicy:
        rule: .*
        didRef: DID0001
- apiVersion: v1draft1
  kind: Domain
  metadata:
    name: Another Office
  spec:
    context:
      domainUri: sip2.local