- apiVersion: v1beta1
  kind: Gateway
  metadata:
    name: Provider Inc.
  spec:
    host: sip.provider.net
    port: 5080
    transport: tcp
    credentials:
      username: 'pbx-1'
      secret: '1234'
- apiVersion: v1beta1
  kind: Gateway
  metadata:
    name: Provider Inc.
  spec:
    host: sip2.provider.net
    transport: tcp
