# Use gateway to register with a Sip Gateways or SBCs and send
# or receive calls from the PSTN
- apiVersion: v1draft1
  kind: Gateway
  metadata:
    name: DID Logic, Inc
    ref:  GW0001
  spec:
    regService:
      username: '96170'
      secret: TH9BTbsQcsEpdgpa
      host: sip.didlogic.net
      transport: udp
      registries: [sip.nyc.didlogic.net]