- apiVersion: v1draft1
  kind: Gateway
  metadata:
    name: Voip MS
    ref: GW0001
  spec:
    regService:
      host: sanjose2.voip.ms
      credentials:
        username: '215706'
        secret: 'iymscvb4rUSG4T0P4RD0'
      transport: tcp
      registries:
        - atlanta2.voip.ms