- apiVersion: v1draft1
  kind: Gateway
  metadata:
    name: SIP Provider
    ref: GW0001
  spec:
    regService:
      host: sip.provider.net
      credentials:
        username: '12345'
        secret: 'supersecret'
      transport: tcp
      registries:
        - sip2.provider.net
