- apiVersion: v1draft1
  kind: Gateway
  metadata:
    name: Your Service Provider
    ref: GW0001
  spec:
    regService:
      host: provider.com
      credentials:
        username: '12345'
        secret: 'supersecret'
      transport: tcp
      registries:
        - host2.provider.com
