# Use gateway to register with a Sip Gateways or SBCs and send
# or receive calls from the PSTN
- kind: Gateway
  apiVersion: v1
  id: '96170'
  metadata:
    name: DID Logic, Inc
    zone: USA / us1
    type: Provider
  username: '96170'
  secret: TH9BTbsQcsEpdgpa
  host: sip.didlogic.net      # Inbound/Outbound host
  registries:                 # Inbound hosts
    - sip.nyc.didlogic.net