# Use gateway to register with a Sip Gateways or SBCs and send
# or receive calls from the PSTN
- apiVersion: v1
  kind: Gateway
  metadata:
    name: DID Logic, Inc
    zone: USA / us1
    type: Provider
    ref:  GW0001
  username: '96170'
  secret: TH9BTbsQcsEpdgpa
  host: sip.didlogic.net      # Inbound/Outbound host
  transport: udp
  registries:                 # Inbound hosts
    - sip.nyc.didlogic.net