# Use gateway to register with a Sip Gateways or SBCs and send
# or receive calls from the PSTN
- apiVersion: v1draft1
  kind: Gateway
  metadata:
    name: DID Logic, Inc
    ref:  GW0001
  spec:
    regService:
      host: sip.provider.net
      credentials:
        username: 'gwuser'
        secret: gwsecret
      transport: udp
      registries: [sip.nyc.provider.net]