# Peers and Agents can register in Sip I/O location service
- kind: Peer
  apiVersion: v1
  metadata:
    name: Asterisk PBX 13
    type: MediaServer
    desc: Default Media Server
  username: ms
  secret: 1c3cr34m
  host: 192.168.1.6
  port: 5060                  # Not using this yet
