- kind: Peer
  apiVersion: v1
  metadata:
    name: DID Logic, Inc
    zone: USA / us1
    id: 96170
  username: '96170'
  secret: TH9BTbsQcsEpdgpa
  # outboundProxy:
  # port:
  # authUser:
  host: sip.didlogic.net      # Inbound/Outbound host
  registries:                 # Inbound hosts
    - sip.nyc.didlogic.net

- kind: Peer
  apiVersion: v1
  metadata:
    name: Asterisk PBX 13
    desc: Media Server
  username: ms
  secret: 1c3cr34m
  host: 127.0.0.1
  port: 5060                  # Not using this yet
