apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include ".helm2.fullname" . }}
  labels:
    {{- include ".helm2.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include ".helm2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include ".helm2.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: routr
        image: "{{ .Values.routr.image.repository }}:{{ .Values.routr.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.routr.image.pullPolicy }}
        env:
        - name: DATA_SOURCE_PROVIDER
          value: {{ .Values.routr.dataSource.provider }}
        - name: DATA_SOURCE_PARAMETERS
          # TODO: Change attempt to take this value directly from subchart
          value: {{ .Values.routr.dataSource.parameters | quote }}
          # TODO: Fix hardcode
        - name: EXTERN_ADDR
          value: {{ .Values.routr.externAddr | quote }}
        ports:
        - name: {{ .Values.routr.adminService.name }}
          containerPort: {{ .Values.routr.adminService.containerPort | default .Values.routr.adminService.port }}
          protocol: TCP
        {{- if eq .Values.routr.udpSignalingService.enabled true }}
        - name: {{ .Values.routr.udpSignalingService.name }}
          containerPort: {{ .Values.routr.udpSignalingService.containerPort | default .Values.routr.udpSignalingService.port }}
          protocol: UDP
        {{- end }}
        {{- range .Values.routr.tcpSignalingService.ports }}
        - name: {{ .name }}
          containerPort: {{ .containerPort | default .port }}
          protocol: TCP
        {{- end }}
        volumeMounts:
        - name: log4j2
          mountPath: /opt/routr/config/log4j2.yml
          subPath: log4j2.yml
        - name: config
          mountPath: /opt/routr/config/config.yml
          subPath: config.yml
      volumes:
      - configMap:
          name: {{ include ".helm2.fullname" . }}-log4j2
        name: log4j2
      - configMap:
          name: {{ include ".helm2.fullname" . }}-config
        name: config
