apiVersion: v1
kind: Service
metadata:
  name: {{ include ".helm2.fullname" . }}
  labels:
    {{- include ".helm2.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  {{- if ne .Values.service.type "ClusterIP" }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
  {{- range .Values.service.ports }}
  {{- if eq .enabled true }}
  - name: {{ .name }}
    port: {{ .port }}
    protocol: {{ .protocol | default `TCP` }}
    targetPort: {{ .targetPort | default .port }}
  {{- end }}
  {{- end }}
  selector:
    {{- include ".helm2.selectorLabels" . | nindent 4 }}
