name: Build Routr Documentation
on: [push]
jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build docs with mkdocs
        run: |
          sudo apt-get update
          sudo apt-get install -y mkdocs
          mkdocs build
          ls .
