name: Publish to Docker Registry
on:
  push:
    tags: ['1.0.0-rc*']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get the version
        id: get_version
        run: echo ::set-output name=ROUTR_VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Publish to Registry(pushed tag)
        env:
          ROUTR_VERSION: ${{ steps.get_version.outputs.ROUTR_VERSION }}
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: fonoster/routr
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: .docker
          buildargs: ROUTR_VERSION
          tag_names: true
      - name: Publish to Registry(latest tag)
        env:
          ROUTR_VERSION: ${{ steps.get_version.outputs.ROUTR_VERSION }}
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: fonoster/routr
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: .docker
          buildargs: ROUTR_VERSION
