name: Routr Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: toolmantim/release-drafter@v5.2.0
        template: |
          ## What’s Changed

          $CHANGES      
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Release.txt
          asset_name: Release2.txt
          tag: 1.0.0-rcx
