name: Publish to Snapcraft marketplace
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.SNAPCRAFT_TOKEN }}
      - name: Build and publish snap
        env:
          ROUTR_VERSION: 1.0.0-rc4
          SNAPCRAFT_BUILD_ENVIRONMENT: host
        run: |
          cd .snapcraft
          snapcraft snap --output=routr-server_$ROUTR_VERSION_amd64.snap
          snapcraft push --release=candidate routr-server_$ROUTR_VERSION_amd64.snap

#ROUTR_VERSION: ${{ steps.get_version.outputs.ROUTR_VERSION }}
  #push:
  #  tags: ['1.0.0-rc*']
